jobs:
- job:
  displayName: 'vs2017-win2016'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - powershell: |
      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      Write-Host "##vso[task.setvariable variable=CONDAPS1]$env:CONDA\shell\condabin\conda-hook.ps1"
    displayName: Add conda to PATH

  - script: |
      conda create --yes --quiet --name chihiro
    displayName: Create Anaconda environment

  - script: |
      call activate chihiro
      conda install --yes --quiet --name chihiro openssl
    displayName: Install Anaconda packages

  - script: |
      call activate chihiro
      call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      set CC=cl.exe
      set CXX=cl.exe
      cmake -G "NMake Makefiles" -B build -DCMAKE_BUILD_TYPE=Release
      cmake --build build
    displayName: Compile

  # - powershell: |
  #     . $Env:CONDAPS1
  #     conda activate chihiro
  #     New-Item -Name build -ItemType directory
  #     cmake -G "NMake Makefiles" -B build -DCMAKE_BUILD_TYPE=Release
  #     cmake --build build
